[package]
name = "gravel"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2.3.2"


[profile.release]
lto = true
codegen-units = 1
opt-level = 3